source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "bulma-rails",          "~> 0.4"
gem "enumerize",            "~> 2.1"
gem "jquery-rails",         "~> 4.3"
gem "font-awesome-rails",   "~> 4.7"
gem "pry",                  "~> 0.10"
gem "http_accept_language", "~> 2.1"
gem "capistrano",           "~> 3.8"

gem 'listen',               ">= 3.0.5", "< 3.2"
gem 'meta-tags',    '~> 2.6'

gem 'rails',        '~> 5.1.2'
gem 'pg',           '~> 0.18'
gem 'puma',         '~> 3.7'
gem 'sass-rails',   '~> 5.0'
gem 'uglifier',     '>= 1.3.0'
gem 'redis',        '~> 4.0'
gem 'coffee-rails', '~> 4.2'
gem 'turbolinks',   '~> 5'
gem 'jbuilder',     '~> 2.5'

group :development, :test, :production do
  gem "capistrano-rails",     "~> 1.3"
  gem "capistrano-chruby",    "~> 0.1"
  gem "capistrano3-puma",     "~> 3.1"
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'rspec-rails', '~> 3.5'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
