development:
  database:
  workingDir:
  outputFileName:
  yandexApiKey:
  yandexApiUrl:
  wordReferenceApiKeys:
  wordReferenceApiUrlPrefix:
  wordReferenceApiUrlSuffix:

staging:

test:

production:
