production:
  database: subtitre_production
  logFile: wall-e.log
  yandexApiKey: a
  yandexApiUrl: b
  wordReferenceApiKeys: [pass1, pass2]
  wordReferenceApiUrlPrefix: http://api.wordreference.com/
  wordReferenceApiUrlSuffix: /json/
  wordReferencePool: 5
