development:
  database:
  workingDir:
  outputFileName:
  pgPool:
  yandexApiKey:
  yandexApiUrl:
  wordReferenceApiKeys:
  wordReferenceApiUrlPrefix:
  wordReferenceApiUrlSuffix:
  wordReferencePool:

staging:

test:

production:
